// Auto-generated by verification/sv_vector_bridge.py
// Source of truth: NOC_PQATTEST.srcs/sources_1/new/NOC_PKG.sv

localparam int VECTOR_0_FLIT_COUNT = 2;

noc_pkg::flit_t VECTOR_0_FLITS [0:1];

assign VECTOR_0_FLITS[0].flit_data = 32'h40001000;
assign VECTOR_0_FLITS[0].flit_type = noc_pkg::FLIT_HEAD;
assign VECTOR_0_FLITS[0].vc_id = noc_pkg::vc_e'(0);

assign VECTOR_0_FLITS[1].flit_data = 32'h12345678;
assign VECTOR_0_FLITS[1].flit_type = noc_pkg::FLIT_TAIL;
assign VECTOR_0_FLITS[1].vc_id = noc_pkg::vc_e'(0);


// Auto-generated by verification/sv_vector_bridge.py
// Source of truth: NOC_PQATTEST.srcs/sources_1/new/NOC_PKG.sv

localparam int VECTOR_1_FLIT_COUNT = 6;

noc_pkg::flit_t VECTOR_1_FLITS [0:5];

assign VECTOR_1_FLITS[0].flit_data = 32'h04043000;
assign VECTOR_1_FLITS[0].flit_type = noc_pkg::FLIT_HEAD;
assign VECTOR_1_FLITS[0].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_1_FLITS[1].flit_data = 32'h00000001;
assign VECTOR_1_FLITS[1].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_1_FLITS[1].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_1_FLITS[2].flit_data = 32'h00000002;
assign VECTOR_1_FLITS[2].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_1_FLITS[2].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_1_FLITS[3].flit_data = 32'h00000003;
assign VECTOR_1_FLITS[3].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_1_FLITS[3].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_1_FLITS[4].flit_data = 32'h00000004;
assign VECTOR_1_FLITS[4].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_1_FLITS[4].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_1_FLITS[5].flit_data = 32'h00000005;
assign VECTOR_1_FLITS[5].flit_type = noc_pkg::FLIT_TAIL;
assign VECTOR_1_FLITS[5].vc_id = noc_pkg::vc_e'(2);


// Auto-generated by verification/sv_vector_bridge.py
// Source of truth: NOC_PQATTEST.srcs/sources_1/new/NOC_PKG.sv

localparam int VECTOR_2_FLIT_COUNT = 17;

noc_pkg::flit_t VECTOR_2_FLITS [0:16];

assign VECTOR_2_FLITS[0].flit_data = 32'h24058800;
assign VECTOR_2_FLITS[0].flit_type = noc_pkg::FLIT_HEAD;
assign VECTOR_2_FLITS[0].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[1].flit_data = 32'h00000001;
assign VECTOR_2_FLITS[1].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[1].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[2].flit_data = 32'h00000002;
assign VECTOR_2_FLITS[2].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[2].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[3].flit_data = 32'h00000003;
assign VECTOR_2_FLITS[3].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[3].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[4].flit_data = 32'h00000004;
assign VECTOR_2_FLITS[4].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[4].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[5].flit_data = 32'h00000005;
assign VECTOR_2_FLITS[5].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[5].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[6].flit_data = 32'h00000006;
assign VECTOR_2_FLITS[6].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[6].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[7].flit_data = 32'h00000007;
assign VECTOR_2_FLITS[7].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[7].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[8].flit_data = 32'h00000008;
assign VECTOR_2_FLITS[8].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[8].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[9].flit_data = 32'h00000009;
assign VECTOR_2_FLITS[9].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[9].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[10].flit_data = 32'h0000000A;
assign VECTOR_2_FLITS[10].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[10].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[11].flit_data = 32'h0000000B;
assign VECTOR_2_FLITS[11].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[11].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[12].flit_data = 32'h0000000C;
assign VECTOR_2_FLITS[12].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[12].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[13].flit_data = 32'h0000000D;
assign VECTOR_2_FLITS[13].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[13].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[14].flit_data = 32'h0000000E;
assign VECTOR_2_FLITS[14].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[14].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[15].flit_data = 32'h0000000F;
assign VECTOR_2_FLITS[15].flit_type = noc_pkg::FLIT_BODY;
assign VECTOR_2_FLITS[15].vc_id = noc_pkg::vc_e'(2);

assign VECTOR_2_FLITS[16].flit_data = 32'h00000010;
assign VECTOR_2_FLITS[16].flit_type = noc_pkg::FLIT_TAIL;
assign VECTOR_2_FLITS[16].vc_id = noc_pkg::vc_e'(2);
