from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


FLIT_HEAD = 0
FLIT_BODY = 1
FLIT_TAIL = 2
FLIT_HEAD_TAIL = 3

VC_REQUEST = 0
VC_RESPONSE = 1
VC_ATTESTATION = 2

MSG_MEM_RD_REQ = 0
MSG_MEM_RD_RESP = 1
MSG_MEM_WR_REQ = 2
MSG_MEM_WR_RESP = 3
MSG_ATTEST_CHALLENGE = 4
MSG_ATTEST_RESPONSE = 5
MSG_ATTEST_GRANT = 6
MSG_ATTEST_REVOKE = 7


MESSAGE_PAYLOAD_FLITS = {
    MSG_MEM_RD_REQ: 1,
    MSG_MEM_RD_RESP: 1,
    MSG_MEM_WR_REQ: 2,
    MSG_MEM_WR_RESP: 0,
    MSG_ATTEST_CHALLENGE: 5,
    MSG_ATTEST_RESPONSE: 16,
    MSG_ATTEST_GRANT: 0,
    MSG_ATTEST_REVOKE: 0,
}

MESSAGE_VC = {
    MSG_MEM_RD_REQ: VC_REQUEST,
    MSG_MEM_WR_REQ: VC_REQUEST,

    MSG_MEM_RD_RESP: VC_RESPONSE,
    MSG_MEM_WR_RESP: VC_RESPONSE,

    MSG_ATTEST_CHALLENGE: VC_ATTESTATION,
    MSG_ATTEST_RESPONSE: VC_ATTESTATION,
    MSG_ATTEST_GRANT: VC_ATTESTATION,
    MSG_ATTEST_REVOKE: VC_ATTESTATION,
}


FLIT_TYPE_NAMES = {
    FLIT_HEAD: "FLIT_HEAD",
    FLIT_BODY: "FLIT_BODY",
    FLIT_TAIL: "FLIT_TAIL",
    FLIT_HEAD_TAIL: "FLIT_HEAD_TAIL",
}


@dataclass(frozen=True)
class Packet:
    source_x: int
    source_y: int
    dest_x: int
    dest_y: int
    msg_type: int
    control: int
    vc: int
    payload: tuple[int, ...]


def expected_payload_count(msg_type: int) -> int:
    if msg_type not in MESSAGE_PAYLOAD_FLITS:
        raise ValueError(f"Unsupported msg_type: {msg_type}")

    return MESSAGE_PAYLOAD_FLITS[msg_type]


def expected_vc(msg_type: int) -> int:
    if msg_type not in MESSAGE_VC:
        raise ValueError(f"Unsupported msg_type: {msg_type}")

    return MESSAGE_VC[msg_type]


def expected_length(msg_type: int) -> int:
    return 1 + expected_payload_count(msg_type)


def pack_head_data(packet: Packet) -> int:
    """
    Exact 32-bit packed head_flit_t representation from NOC_PKG.sv.

    head_flit_t:
        dest_x  [2:0]
        dest_y  [2:0]
        src_x   [2:0]
        src_y   [2:0]
        msg     [3:0]
        length  [4:0]
        control [10:0]
    """

    value = 0

    value |= (packet.dest_x & 0x7) << 29
    value |= (packet.dest_y & 0x7) << 26
    value |= (packet.source_x & 0x7) << 23
    value |= (packet.source_y & 0x7) << 20
    value |= (packet.msg_type & 0xF) << 16
    value |= (expected_length(packet.msg_type) & 0x1F) << 11
    value |= packet.control & 0x7FF

    return value


def validate_packet(packet: Packet) -> None:
    for name, value in (
        ("source_x", packet.source_x),
        ("source_y", packet.source_y),
        ("dest_x", packet.dest_x),
        ("dest_y", packet.dest_y),
    ):
        if not 0 <= value < 8:
            raise ValueError(f"{name} must be 0..7")

    if not 0 <= packet.msg_type < 16:
        raise ValueError("msg_type must be 0..15")

    if not 0 <= packet.control < 2048:
        raise ValueError("control must be 0..2047")

    if not 0 <= packet.vc < 4:
        raise ValueError("vc must be 0..3")

    expected_vc_value = expected_vc(packet.msg_type)

    if packet.vc != expected_vc_value:
        raise ValueError(
            f"msg_type {packet.msg_type} requires VC "
            f"{expected_vc_value}, got {packet.vc}"
        )

    expected_payload = expected_payload_count(packet.msg_type)

    if len(packet.payload) != expected_payload:
        raise ValueError(
            f"msg_type {packet.msg_type} requires "
            f"{expected_payload} payload flits, got {len(packet.payload)}"
        )

    for index, payload in enumerate(packet.payload):
        if not 0 <= payload < (1 << 32):
            raise ValueError(
                f"payload[{index}] is not a 32-bit unsigned value"
            )


def make_flits(packet: Packet) -> list[dict]:
    validate_packet(packet)

    head_data = pack_head_data(packet)

    flits = [
        {
            "flit_type": (
                FLIT_HEAD_TAIL
                if len(packet.payload) == 0
                else FLIT_HEAD
            ),
            "vc": packet.vc,
            "data": head_data,
        }
    ]

    for index, payload in enumerate(packet.payload):

        if index == len(packet.payload) - 1:
            flit_type = FLIT_TAIL
        else:
            flit_type = FLIT_BODY

        flits.append(
            {
                "flit_type": flit_type,
                "vc": packet.vc,
                "data": payload,
            }
        )

    return flits


def generate_sv(packet: Packet, name: str) -> str:
    flits = make_flits(packet)

    lines = [
        "// Auto-generated by verification/sv_vector_bridge.py",
        "// Source of truth: NOC_PQATTEST.srcs/sources_1/new/NOC_PKG.sv",
        "",
        f"localparam int {name}_FLIT_COUNT = {len(flits)};",
        "",
        f"noc_pkg::flit_t {name}_FLITS [0:{len(flits) - 1}];",
        "",
    ]

    for index, flit in enumerate(flits):

        enum_name = FLIT_TYPE_NAMES[flit["flit_type"]]

        lines.extend(
            [
                f"assign {name}_FLITS[{index}].flit_data = "
                f"32'h{flit['data']:08X};",

                f"assign {name}_FLITS[{index}].flit_type = "
                f"noc_pkg::{enum_name};",

                f"assign {name}_FLITS[{index}].vc_id = "
                f"noc_pkg::vc_e'({flit['vc']});",

                "",
            ]
        )

    return "\n".join(lines)


def packet_from_json(obj: dict) -> Packet:

    payload = tuple(
        int(x, 0) if isinstance(x, str) else int(x)
        for x in obj.get("payload", [])
    )

    msg_type = int(obj["msg_type"])

    return Packet(
        source_x=int(obj["source_x"]),
        source_y=int(obj["source_y"]),
        dest_x=int(obj["dest_x"]),
        dest_y=int(obj["dest_y"]),
        msg_type=msg_type,
        control=int(obj.get("control", 0)),
        vc=expected_vc(msg_type),
        payload=payload,
    )


def main() -> int:

    parser = argparse.ArgumentParser(
        description="PQ-Attest P3-2 SV vector bridge"
    )

    parser.add_argument(
        "--input",
        type=Path,
        required=True,
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "verification/generated_sv_vector.sv"
        ),
    )

    parser.add_argument(
        "--name",
        default="VECTOR",
    )

    args = parser.parse_args()

    data = json.loads(
        args.input.read_text(encoding="utf-8")
    )

    if "packets" not in data:
        raise ValueError(
            "Input JSON must contain a 'packets' array"
        )

    packets = [
        packet_from_json(packet)
        for packet in data["packets"]
    ]

    generated = []

    for index, packet in enumerate(packets):
        generated.append(
            generate_sv(
                packet,
                f"{args.name}_{index}",
            )
        )

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    args.output.write_text(
        "\n\n".join(generated),
        encoding="utf-8",
    )

    print("PQ-ATTEST P3-2 SV VECTOR BRIDGE")
    print(f"PACKETS : {len(packets)}")
    print(f"OUTPUT  : {args.output}")
    print("STATUS  : PASS")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
